version: "3.9"

services:
  frontend:
    hostname: frontend
    build: ./client
    image: frontend:1.0
    ports:
      - "8081:80"
    links:
      - backend
  backend:
    hostname: backend
    build: ./server
    image: backend:1.0
    ports:
      - "5001:5000"
